# Generated by Django 5.1.4 on 2024-12-22 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_level_remove_task_description_task_full_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='admin_comment',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='usertask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='usertask',
            name='need_verify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usertask',
            name='worker_comment',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='UserTaskFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='tasks/')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='task.usertask')),
            ],
        ),
        migrations.CreateModel(
            name='UserTaskLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='task.usertask')),
            ],
        ),
    ]
