# Generated by Django 5.1.4 on 2024-12-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_usertask_task_alter_usertask_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='decline',
            field=models.BooleanField(default=False, verbose_name='Отказался'),
        ),
        migrations.AddField(
            model_name='usertask',
            name='need_extra_work',
            field=models.BooleanField(default=False, verbose_name='На доработке'),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='need_verify',
            field=models.BooleanField(default=False, verbose_name='Нужна проверка'),
        ),
    ]
