# Generated by Django 5.1.4 on 2025-01-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_file_name_link_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='timeout',
            field=models.BooleanField(default=False, verbose_name='Просрочено'),
        ),
    ]
