# Generated by Django 5.1.4 on 2024-12-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_firstname_alter_user_lastname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wallet',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
