# Generated by Django 5.1.4 on 2024-12-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='userservice',
            name='code',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userservice',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
