# Generated by Django 5.1.4 on 2025-01-05 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_withdrawalrequest_options_alter_user_firstname_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='withdrawalrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Запрос на вывод', 'verbose_name_plural': '2. Запрос на вывод'},
        ),
    ]
